---
name: Build Finanzly Frontend using environment variable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: Finanzly_Frontend_Production_Env # <---- Ambiente configurado com o segredo API_BASE_URL

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
            API_BASE_URL: ${{ secrets.API_BASE_URL }}  # usar o segredo configurado no ambiente Finanzly_Frontend_Production_Env

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build